# ---------------------------------------------------------------
#  This is a development purpose, auto building docker-compose
#  configuration
# ---------------------------------------------------------------
version: '2'
services:
  be:
    build:
      context: ./
      dockerfile: dockerfile
    command: sanic det.app --dev --host=0.0.0.0 --port=8000 --workers=2
    environment:
      # disabling numpy threads improves multiprocessing speed
      - OPENBLAS_NUM_THREADS=1
      - NUMEXPR_NUM_THREADS=1
      - VECLIB_MAXIMUM_THREADS=1
      - MKL_NUM_THREADS=1
      - OMP_NUM_THREADS=1
      - JWT_SECRET=crrf-det-jwt-SECRET!!!501015
      - URL_SIGN_SECRET=86c935bc079ba1fef55809e2f575426c
    volumes:
      - ./src:/det
      - ./dev-data/data:/data
    ports:
      - 8000:8000
    depends_on:
      - redis
  redis:
    image: redis
    container_name: det-redis
    network_mode: host
    expose:
      - "6379"
    volumes:
      - ./dev-data/huey_data:/huey_data
    restart: "unless-stopped"
    command: redis-server --save 3600 1 --loglevel warning
