#!/bin/bash

BUILD_OPTS="-DBUILD_GTK_TESTS=OFF -DBUILD_QT5_TESTS=OFF -DBUILD_QT6_TESTS=OFF -DBUILD_CPP_TESTS=OFF -DENABLE_GLIB=OFF -DENABLE_GOBJECT_INTROSPECTION=OFF -DENABLE_QT5=OFF -DENABLE_QT6=OFF"

cmake -GNinja -S poppler-0.90.1/ -B poppler-debug/ -DCMAKE_BUILD_TYPE=Debug $BUILD_OPTS && cmake --build poppler-debug/ -j
